services:
  code-paste:
    image: ghcr.io/yueli-official/code-paste:latest
    container_name: code-paste
    platform: linux/amd64
    ports:
      - "9000:9000"
    volumes:
      # 挂载数据库
      - ./data:/app/data
    environment:
      # 数据库路径
      - DATABASE_URL=/app/data/snippets.db
